// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"
)

type Widget struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
