// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: widgets.sql

package dbgen

import (
	"context"
	"time"
)

const createWidget = `-- name: CreateWidget :one
INSERT INTO widgets (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateWidget(ctx context.Context, name string) (Widget, error) {
	row := q.db.QueryRow(ctx, createWidget, name)
	var i Widget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWidget = `-- name: DeleteWidget :execrows
DELETE FROM widgets
WHERE id = $1
`

func (q *Queries) DeleteWidget(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWidget, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWidget = `-- name: GetWidget :one
SELECT id, name, created_at, updated_at
FROM widgets
WHERE id = $1
`

func (q *Queries) GetWidget(ctx context.Context, id int64) (Widget, error) {
	row := q.db.QueryRow(ctx, getWidget, id)
	var i Widget
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWidgets = `-- name: ListWidgets :many
SELECT id, name, created_at, updated_at
FROM widgets
ORDER BY created_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListWidgets(ctx context.Context, limit int32) ([]Widget, error) {
	rows, err := q.db.Query(ctx, listWidgets, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Widget{}
	for rows.Next() {
		var i Widget
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWidgetsAfter = `-- name: ListWidgetsAfter :many
SELECT id, name, created_at, updated_at
FROM widgets
WHERE (created_at, id) < ($1::timestamptz, $2::bigint)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListWidgetsAfterParams struct {
	CursorCreatedAt time.Time
	CursorID        int64
	PageLimit       int32
}

// Row comparison, not the equivalent OR form: it matches the leading columns of
// widgets_created_at_id_idx so the planner can start the scan at the cursor.
// The casts are required because sqlc otherwise infers both row-constructor
// arguments from the first column and types cursor_id as a timestamp.
func (q *Queries) ListWidgetsAfter(ctx context.Context, arg ListWidgetsAfterParams) ([]Widget, error) {
	rows, err := q.db.Query(ctx, listWidgetsAfter, arg.CursorCreatedAt, arg.CursorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Widget{}
	for rows.Next() {
		var i Widget
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
